[assembly.1] # Assembly name

# Filtering options
use_svm_filter = 1
use_threshold_filter = 100
svm_after_threshold = 0

# Assembly options
assembler = 'soft'


[assembly.2] # Assembly name

# Filtering options
use_svm_filter = 1
use_threshold_filter = 100
svm_after_threshold = 0

# Assembly options
assembler = 'greedy'